export const ALBUM_LIST_REQUEST = 'ALBUM_LIST_REQUEST';
export const ALBUM_LIST_SUCCESS = 'ALBUM_LIST_SUCCESS';
export const ALBUM_REQUEST = 'ALBUM_REQUEST';
export const ALBUM_SUCCESS = 'ALBUM_SUCCESS';
export const SELECT_ALBUM = 'SELECT_ALBUM';
export const SELECT_PHOTO = 'SELECT_PHOTO';